spring:
  application:
    name: LibraryApp
    host: localhost
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  database:
    hostname: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_NAME}
    enumName: book_enum
  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    enabled: true
    locations: classpath:db/migrates
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    baselineOnMigrate: true
server:
  port: 8080
logging:
  level:
    org.springframework.r2dbc.core: INFO
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql: INFO